Adding missing integration test check

diff --git a/.github/actions/build-integration-test/action.yml b/.github/actions/build-integration-test/action.yml
--- a/.github/actions/build-integration-test/action.yml
+++ b/.github/actions/build-integration-test/action.yml
@@ -70,3 +70,11 @@ runs:
         BUILD_TYPE_LOWER=$(echo "${{ inputs.build_type }}" | tr '[:upper:]' '[:lower:]')
         cd "${{ github.workspace }}/IntegrationTests/${{ inputs.integration_test_dir }}/"
         cmake --build --preset conan-$BUILD_TYPE_LOWER
+
+        OUTPUT=$(ctest --test-dir "${BUILD_DIR}" -C "${BUILD_TYPE}" -V)
+        echo "$OUTPUT"
+
+        if echo "$OUTPUT" | grep -q "No tests were found!!!"; then
+          echo "Integration tests not found. Are you in the right directory?"
+          exit 1
+        fi
